config/routes.rb
Rails.application.routes.draw do

  get '/profile' => "users#show"
  get '/profile/edit' => "users#edit"
  patch '/profile/edit' => "users#update"
  get '/profile/myproperties' => "properties#index_profile"
  get '/profile/addproperty' => "properties#new"
  get '/profile/mybookings' => "bookings#show"
  get 'contact' => "pages#contact"
  get 'about' => "pages#about"
  get 'socialmedia' => "pages#social_media"

  devise_for :users
  resources :availabilities
  resources :properties, except: [:show]

  resources :searches, only: [:show] do
    resources :properties, only: [:show] do
      resources :bookings, only: [:new]
    end
  end

  resources :bookings, only: [:create, :destroy]
  resources :searches, only: [:new, :create]
  root 'searches#new'

end

app/models/availability.rb
class Availability < ActiveRecord::Base
  belongs_to :property
  has_many :bookings, through: :property

   def self.search(query = {})
    # where(:title, query) -> This would return an exact match of the query
    search_scope = joins(:property)
    search_scope = search_scope.where("availabilities.capacity >= ?", "#{query.capacity}") if query.capacity.present?
    search_scope = search_scope.where("availabilities.start_date <= ?", "#{query.start_date}") if query.start_date.present?
    search_scope = search_scope.where("availabilities.end_date >= ?", "#{query.end_date}") if query.end_date.present?
    search_scope = search_scope.where("properties.country like ?", "#{query.country}") if query.country.present?
    search_scope = search_scope.where("properties.price_night <= ?", "#{query.price_night}") if query.price_night.present?
    search_scope
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :property
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :availabilities
  belongs_to :user
  has_many :bookings
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :properties
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def show
    @bookings = current_user.bookings
    @total = 0
    @price = 0
  end

  def new
    @booking = Booking.new
    @search = Search.find(params[:search_id])
    @property = Property.find(params[:property_id])
  end

  def create
    @booking = Booking.create(booking_params)
    redirect_to root_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to profile_mybookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:property_id, :user_id, :start_date, :end_date, :capacity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def social_media
  end

  def contact
  end


end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @properties = Property.all
  end

  def index_profile
    @properties = current_user.properties
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.create(property_params)
    redirect_to profile_myproperties_path
  end

  def edit
     @property = Property.find(params[:id])
  end

  def update
  @property = Property.find(params[:id])
  @property.update(property_params)
  redirect_to property_path(@property)
  end

  def destroy
         @property = Property.find(params[:id])
         @property.destroy
        redirect_to properties_path

  end

private

  def property_params
    params.require(:property).permit(:name, :country, :beach_name, :price_night, :capacity, :user_id)
  end


end

app/controllers/searches_controller.rb
require 'date'

class SearchesController < ApplicationController
  def new
    @search = Search.new
  end

  def create
    params[:search][:start_date] = Date.strptime(params[:search][:start_date],"%m/%d/%Y") if !params[:search][:start_date].empty?
    params[:search][:end_date] = Date.strptime(params[:search][:end_date],"%m/%d/%Y") if !params[:search][:end_date].empty?
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
    availabilities = Availability.search(@search).order("created_at DESC")
    @final = show_date(availabilities, @search).uniq
    @props = []
    @final.each do |av|
      @props << av.property
    end
    @markers = Gmaps4rails.build_markers(@props) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end

  private

  def search_params
    params.require(:search).permit(:country, :price_night, :capacity, :start_date, :end_date)
  end

  def show_date(availabilities, search)
    final = []
    temp = []
    availabilities.each do |availability|
      if availability.property.bookings.empty?
        final << availability
      else
        availability.property.bookings.each do |booking|
          (booking.start_date..booking.end_date).each do |date|
            temp << false  if search_date_in_booking_date(date, search)
          end
        end
      end
      final << availability if !temp.include?(false)
    end
    return final
  end

  def search_date_in_booking_date(date, search)
    (search.start_date..search.end_date).cover?(date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to @user
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user.update(user_params)
    redirect_to profile_path
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :country, :first_name, :last_name, :city, :zipcode, :house_number, :phone_number, :street_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <p>Name: <%= @property.name %></p>
      <p>On: <%= @property.beach_name %></p>
      <p>Price for a night:<%= @property.price_night %></p>
      <p>From: <%= @search.start_date %></p>
      <p>To: <%= @search.end_date %></p>
      <p>Capacity: <%= @search.capacity %></p>

      <%= simple_form_for(@booking) do |f| %>
      <div class="form-inputs">
        <%= f.hidden_field :start_date, value: @search.start_date %>
        <%= f.hidden_field :end_date, value: @search.end_date %>
        <%= f.hidden_field :capacity, value: @search.capacity %>
        <%= f.hidden_field :beach_name, value: @property.beach_name %>
        <%= f.hidden_field :price_night, value: @property.price_night %>
        <%= f.hidden_field :property_id, value: @property.id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
      <div class="form-actions">
        <%= f.submit "Confirm booking" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div id="wrapper">
        <%= render partial: "shared/side_bar" %>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                      <table class="table table-hover table-striped table-responsive">
                        <thead>
                          <tr>
                            <th>
                              Cabana
                            </th>
                            <th>
                              Country
                            </th>
                            <th>
                              To
                            </th>
                            <th>
                              From
                            </th>
                            <th>
                              Total price
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @bookings.each do |b| %>
                            <tr>
                              <td><%= b.property.name %></td>
                              <td><%= b.property.country %></td>
                              <td><%= b.start_date %></td>
                              <td><%= b.end_date %></td>
                              <td> <%= @price = (b.end_date - b.start_date) * b.property.price_night %> euro</td>
                              <td><%= link_to "Cancel booking", booking_path(b), method: "delete" , class: "btn btn-primary" %></td>
                              <% @total += @price %>
                            </tr>
                          <% end %>
                          <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>Total</td>
                            <td>
                              <%= @total %> euro
                            </td>
                          </tr>
                        </tbody>
                      </table>
                      </div>
                    </div>
                  </div>
                  <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Menu Toggle Script -->
<script>
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Cabanas</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
      <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

<body>
  <%= render 'shared/flashes' %>
  <%= render 'shared/navbar' %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
  <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

  <%= javascript_include_tag "application" %>
  <%= yield %>
  <%= yield(:after_js) %>

</body>

</html>

app/views/pages/about.html.erb
<h1>ABOUT</h1>

app/views/pages/contact.html.erb
<H1>Hello "user.name"</H1>
<H2>How can we help you ?</H2>

<%= form_for @message, url: contact_path do |message_form| %>
  <fieldset>
    <div class="field">
      <%= message_form.text_field :name, placeholder: "Name" %>
    </div>

    <div class="field">
      <%= message_form.email_field :email, placeholder: "Email"%>
    </div>

    <div class="field">
      <%= message_form.text_area :content, placeholder: "Message"%>
    </div>
  </fieldset>

  <fieldset>
    <div class="field">
      <%= message_form.submit "Send" %>
    </div>
  </fieldset>
<% end %>

app/views/pages/social_media.html.erb
<div class="background-socialmedia">
  <div class="container">
    <div class="row">

        <div class="col-sm-12 col-md-4 hovercolor">
        <a href="https://www.facebook.com/"><img src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/facebook_circle_color-256.png"border="0" alt="clic to visit our Instagram"></a>
        </div>


        <div class="col-sm-12 col-md-4 hovercolor">
        <a href="https://twitter.com/"><img src=" https://cdn3.iconfinder.com/data/icons/free-social-icons/67/twitter_circle_color-256.png"border="0" alt="clic to visit our Instagram"></a>
        </div>



        <div class="col-sm-12 col-md-4 hovercolor">
          <a href="https://instagram.com/"><img src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/instagram_circle_color-256.png" border="0" alt="clic to visit our Instagram" ></a>
        </div>


    </div>
  </div>
</div>

app/views/properties/create.html.erb
<h1>Properties#create</h1>
<p>Find me in app/views/properties/create.html.erb</p>

app/views/properties/destroy.html.erb
<h1>Properties#destroy</h1>
<p>Find me in app/views/properties/destroy.html.erb</p>

app/views/properties/edit.html.erb
<H1>Create a new proprety</H1>


<%= form_for(@property) do |f| %>
  <%= f.label :name, "name" %>
  <%= f.text_field :name %>

  <%= f.label :country, "country" %>
  <%= f.text_field :country %>

  <%= f.label :beach_name, "beach name" %>
  <%= f.text_field :beach_name %>

  <%= f.label :price_night, "price per night" %>
  <%= f.number_field :price_night %>

 <%= f.label :capacity, "capacity" %>
  <%= f.text_field :capacity %>


  <%= f.submit %>

<% end %>

app/views/properties/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-lg-12">
    <H1>See all properties</H1>
     </div>

    <% @properties.each do |property| %>

      <div class="col-lg-5 text-background">
        <h2><%= property.name %></h2>
        <p> Country: <%= property.country%></p>
        <p> Price <%= property.price_night%> € </p>
        <br>
        <%= link_to "to the property", property_path(property), class: "btn btn-primary" %>
      </div>

      <div class="col-lg-1">
      </div>

      <div class="col-lg-6 photo">
       <p>photo</p>
      </div>


    <% end %>
  </div>
</div>



<br>


<div>
<%= link_to "create a new Property", new_property_path %>
</div>

app/views/properties/index_profile.html.erb
<div id="wrapper">

        <%= render partial: "shared/side_bar" %>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <% @properties.each do |property| %>
                        <%= property.name %>
                        <% end %>
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

app/views/properties/new.html.erb
<div id="wrapper">

        <%= render partial: "shared/side_bar" %>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= simple_form_for(@property) do |f| %>
                          <div class="form-inputs">
                            <%= f.input :name %>
                            <%= f.input :country %>
                            <%= f.input :beach_name %>
                            <%= f.input :price_night %>
                            <%= f.input :capacity %>
                            <%= f.hidden_field :user_id, value: current_user.id %>
                          </div>
                          <div class="form-actions">
                            <%= f.submit %>
                          </div>
                          <% end %>
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

app/views/properties/show.html.erb
<head><link href='style.css' rel='stylesheet' type='text/css'></head>

<body>

<div class="container">
 <div class="row">

   <div class="col-lg-12">
    <hr>
  </div>

    <div class="col-lg-5 text-background">
      <h1> <%= @property.name %> </h1>
      <p> Country: <%= @property.country %> </p>
      <p> Beach name: <%= @property.beach_name %> </p>
      <p> Price per night: <%= @property.price_night %> € </p>
      <p> Capacity: <%= @property.capacity %> persons </p>
      <br>
      <%= link_to "edit my property", edit_property_path(@property), class: "btn btn-primary"%>
      <%= link_to "delete my property", property_path(@property), method: :delete,class: "btn btn-primary"%>
   </div>

   <div class="col-lg-1">
  </div>

  <div class="col-lg-6 photo">
    <p>photo</p>
  </div>

</div>

 <div class="row">

  <div class="col-lg-6">

    <hr>
    <%= link_to "back to list", properties_path, class: "btn btn-primary text-center"  %>
     <hr>
  </div>
   </div>
</div>
  </div>

</body>

app/views/properties/update.html.erb
<h1>Properties#update</h1>
<p>Find me in app/views/properties/update.html.erb</p>

app/views/searches/new.html.erb
<div class="bg-search-bar">
  <div class="container search-bar">
      <div class="row">
        <div class="col-xs-6 col-xs-offset-3 text-center">
          <%= image_tag 'Drawing', alt: 'logo' %>
          <h1 id="tagline">Paradise is waiting for you ...</h1>
        </div>
      </div>
    </div>
  <div class="container search-bar">
    <div class="row">
      <div class="col-xs-12 col-md-2">
        <%= simple_form_for @search do |f| %>
        <%= f.input :country, label: false, prompt: "Select country", class: "form-control", id: "country" %>
        </div>
        <div class="col-xs-12 col-md-2">
        <%= f.text_field :price_night, class: "form-control", id: "price_night", placeholder: "price/night" %>
        </div>
        <div class="col-xs-12 col-md-2">
        <%= f.text_field :start_date, class: "form-control", id: "start_date", placeholder: "Check in" %>
        </div>
        <div class="col-xs-12 col-md-2">
        <%= f.text_field :end_date, class: "form-control", id: "end_date", placeholder: "Check out" %>
        </div>
        <div class="col-xs-12 col-md-2">
        <%= f.select :capacity, [['1 Guest',1],['2 Guests', 2],['3 Guests', 3],['4 Guests', 4],['5 Guests', 5],['6 Guests', 6],['7 Guests', 7],['8 Guests', 8],['9 Guests', 9],['10 Guests', 10],['11 Guests', 11],['12 Guests', 12],['13 Guests', 13],['14 Guests', 14],['15 Guests', 15],['16 Guests', 16]], {}, class: "form-control" %>
        </div>
        <div class="col-xs-4 col-xs-offset-4 col-md-2 col-md-offset-0 text-center">
          <%= f.submit "Search", class: "btn btn-danger submit-search" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/searches/show.html.erb
<div class="container container_borer ">
  <div class="row">
    <div class="col-xs-12 col-sm-8 boxes_container">
      <div class="row">

        <% @final.each do |a| %>
          <div class="col-xs-12 col-sm-6 box_result">

           <div class="box_image">
            <H4 class="price-image"> <%= a.property.price_night %>€/day </H4>
          <H3><%= link_to "B", new_search_property_booking_path(search_id: @search, property_id: a.property), class: "book-image" %></H3>

           </div>

           <div>
            <H4> <%= a.property.name %> </H4>
            <p> <%= a.property.country %> at <%= a.property.beach_name %></p>

           </div>
          </div>

        <% end %>
      </div>
    </div>

    <div class="col-xs-12 col-sm-4 search_map">
      <div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>
    </div>


</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default main-nav">
  <div class="container-fluid main-nav-container">
    <a class = "navbar-brand">#</a>
    <button class = "navbar-toggle" data-toggle = "collapse" data-target = "#navHeaderCollapse">
      <span class = "icon-bar"></span>
      <span class = "icon-bar"></span>
      <span class = "icon-bar"></span>
    </button>
    <div class = "collapse navbar-collapse" id="navHeaderCollapse">
      <ul class = "nav navbar-nav pull-right">
        <li><%= link_to "Home", '/' %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Social Media", socialmedia_path %></li>
        <li><%= link_to "Contact Us", contact_path %></li>
        <% if user_signed_in? %>
          <li><li><%= link_to "Profile", profile_path %></li></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_side_bar.html.erb
<!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                  <%= link_to "Dashboard", profile_path %>
                </li>
                <li>
                  <%= link_to "Edit your profile", profile_edit_path %>
                </li>
                <% if !current_user.properties.empty? %>
                  <li>
                    <%= link_to "View your properties", profile_myproperties_path %>
                  </li>
                <% end %>
                <li>
                  <%= link_to "Add a property", profile_addproperty_path %>
                </li>
                <% if !current_user.bookings.empty? %>
                  <li>
                    <%= link_to "Manage your bookings", profile_mybookings_path %>
                  </li>
                <% end %>
            </ul>
        </div>

app/views/users/_form.html.erb
<h2>Edit your profile</h2>
<%= simple_form_for current_user, url: profile_edit_path, method: "patch" do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_name, autofocus: true %>
    <%= f.input :first_name, autofocus: true %>
    <%= f.input :last_name, autofocus: true %>
    <%= f.input :street_name, autofocus: true %>
    <%= f.input :house_number, autofocus: true %>
    <%= f.input :city, autofocus: true %>
    <%= f.input :country, autofocus: true %>
    <%= f.input :zipcode, autofocus: true %>
    <%= f.input :phone_number, autofocus: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save changes" %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div id="wrapper">

        <%= render partial: "shared/side_bar" %>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= render partial: "users/form" %>
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div id="wrapper">

        <!-- Sidebar -->
        <%= render partial: "shared/side_bar" %>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>Your profile info</h1>
                        <ul>
                          <li><%= @user.user_name %></li>
                          <li><%= @user.first_name %></li>
                          <li><%= @user.last_name %></li>
                          <li><%= @user.street_name %></li>
                          <li><%= @user.house_number %></li>
                          <li><%= @user.city %></li>
                          <li><%= @user.zipcode %></li>
                          <li><%= @user.country %></li>
                          <li><%= @user.phone_number %></li>
                        </ul>
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>